[workspace]
members = [
	"crates/bot",
	"crates/bot-client",
	"crates/bot-http",
	"crates/git-tracker"
]
resolver = "2"

[workspace.dependencies]
bot = { path = "./crates/bot" }
bot-client = { path = "./crates/bot-client" }
bot-http = { path = "./crates/bot-http" }
git-tracker = { path = "./crates/git-tracker" }

git2 = { version = "0.18.3", default-features = false }
log = "0.4.21"
tokio = { version = "1.38.0", features = [
	"macros",
	"rt-multi-thread",
	"signal"
] }
