name: CI

on:
  push:
    branches: [main]
    paths:
      - "**.nix"
      - "flake.lock"
      - "**.rs"
      - "Cargo.toml"
      - "Cargo.lock"
  pull_request:
    paths:
      - "**.nix"
      - "flake.lock"
      - "**.rs"
      - "Cargo.toml"
      - "Cargo.lock"
  workflow_dispatch:

jobs:
  build:
    name: Build

    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Run build
        run: |
          cargo build --locked --release

  nix:
    name: Nix

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v13

      - name: Setup Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v7

      - name: Run build
        run: nix build --print-build-logs --show-trace

  treefmt:
    name: Treefmt

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v13

      - name: Run check
        run: |
          nix flake check --print-build-logs --show-trace

  release-gate:
    name: CI Release gate
    needs: [build, nix, treefmt]

    runs-on: ubuntu-latest

    steps:
      - name: Exit with error
        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
        run: exit 1
